apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prova
  name: ingress-simpleapp
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app.prova
    http:
      paths:
      - path: /
        backend:
          serviceName: simpleapp
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prova
  name: ingress-kibana
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kibana.prova
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 80