apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simpleapp-prova
  namespace: prova
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "false"   
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: app.prova.9217b2b285d84e2c9841.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: simpleapp-svc
          servicePort: 80
        path: /
