apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-logger
  namespace: giropops
  # annotations:
  #   co.elastic.logs.json-logging/json.keys_under_root: "true"
  #   co.elastic.logs.json-logging/json.add_error_key: "true"
  #   co.elastic.logs.json-logging/json.message_key: "message"
  labels:
    app: random-logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-logger
  template:
    metadata:
      labels:
        app: random-logger
    spec:
      containers:
        - name: random-logger
          image: chentex/random-logger
          imagePullPolicy: Always